# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11src/message.proto\x12\x04\x62\x61nk\"Q\n\x12MsgDeliveryRequest\x12\n\n\x02id\x18\x01 \x01(\x12\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x03\x12\r\n\x05\x63lock\x18\x04 \x01(\x03\"S\n\x10MsgDeliveryReply\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x03\x12\r\n\x05\x63lock\x18\x04 \x01(\x03\x32P\n\x0b\x42\x61nkService\x12\x41\n\x0bMsgDelivery\x12\x18.bank.MsgDeliveryRequest\x1a\x16.bank.MsgDeliveryReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MSGDELIVERYREQUEST']._serialized_start=27
  _globals['_MSGDELIVERYREQUEST']._serialized_end=108
  _globals['_MSGDELIVERYREPLY']._serialized_start=110
  _globals['_MSGDELIVERYREPLY']._serialized_end=193
  _globals['_BANKSERVICE']._serialized_start=195
  _globals['_BANKSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
